// src/redux/tagTypes/tagTypes.ts
export enum tagTypes {
  USER = "USER",
  BRAND = "BRAND",
  CATEGORY = "CATEGORY",
  PRODUCT = "PRODUCT",
  CART = "CART",
  WISHLIST = "WISHLIST",
  PAYMENT = "PAYMENT",
  FILTER_OPTION = "FILTER_OPTION",
  PRODUCT_QUESTION = "PRODUCT_QUESTION",
  PRODUCT_ANSWER = "PRODUCT_ANSWER",
  PRODUCT_SPECIFICATION = "PRODUCT_SPECIFICATION",
  REVIEW = "REVIEW",
  ORDER = "ORDER",
  DASHBOARD_ANALYTICS = "DASHBOARD_ANALYTICS",
}
